### ISSUE TITLE
GitHub Actions NullPointer

### ISSUE THREAD

**Issue by cah-joeymadich** [djspiewak/sbt-github-packages#23]
Receiving this consistently using the plugin version 0.5.2 for an internal/private, org-based repository.

Actions yaml file...

```
name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: sbt test
      env:
        GITHUB_TOKEN: ${{ secrets.CAH_PUBLISH }}
        GITHUB_ACTOR: "${{ github.actor }}"
    - name: Publish artifacts
      run: sbt publish
      env:
        GITHUB_TOKEN: ${{ secrets.CAH_PUBLISH }}
        GITHUB_ACTOR: ${{ github.actor }}
```

In build.sbt...
```
githubOwner := "cahcommercial"
githubRepository := "gatling-jdbc"
githubTokenSource := TokenSource.Environment("GITHUB_TOKEN")
```

Error (as much as I could copy from github actions log in the web UI)
```
[error] java.lang.NullPointerException
[error] 	at okhttp3.JavaNetAuthenticator.authenticate(JavaNetAuthenticator.java:37)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:284)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:152)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
[error] 	at okhttp3.RealCall.execute(RealCall.java:69)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:186)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:499)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:498)
```

**Comment by djspiewak** [comment]
I think you want `GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}`. The angle brackets seem like the problem here.

**Comment by cah-joeymadich** [comment]
> I think you want `GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}`. The angle brackets seem like the problem here.

sorry that's a bit confusing.. our actual file doesn't include them I was just obfuscating the name. We used either secrets.GITHUB_TOKEN or whatever our personal access token was named.

**Comment by djspiewak** [comment]
If you look in the GitHub Actions log, expand the exact *step* which runs sbt, and then expand the top-most expandable thingy within that step. This should be a print out of all of the environment variables which are in-scope for the run. Double check to make sure that `GITHUB_TOKEN` is set (its value will be obfuscated).

Also it occurs to me that we check `TokenSource.Environment` to ensure the value is set, so this *probably* isn't it. You are definitely seeing some sort of bizarre authentication problem though. Let's try to simplify this down a bit…

- Can you reproduce this outside of GitHub Actions?
- Try removing the `GITHUB_ACTOR` environment variable (it isn't necessary any longer)
- What `resolvers` do you have aside from those provided by this plugin? Can you remove some of them and still reproduce the issue?

Let's try to get the smallest possible build in the most controlled possible environment which reproduces the problem.

**Comment by cah-joeymadich** [comment]
@djspiewak 
✅ removed the GITHUB_ACTOR variable
✅ confirmed we're not using any additional resolvers
✅ confirmed I could see the obfuscated GITHUB_TOKEN used in the sbt publish command w/in the action logs

I deleted the package from the registry as an earlier broken pipe exception seemingly left it in a partially published state... I ran the action again and it published successfully! Weird... Now when I try to push updates I get the error you mentioned requiring me to use personal access tokens with read-package scope enabled.
```
[error] java.io.IOException: PUT operation to URL https://maven.pkg.github.com/cahcommercial/gatling-jdbc/com/cah/commtech/jdbc-gatling_2.12/2.3.1-SNAPSHOT/jdbc-gatling_2.12-2.3.1-SNAPSHOT.pom failed with status code 422: Unprocessable Entity
```
When using the personal access tokens, would I want to set the GITHUB_ACTOR env var along with using the personal access token from secrets?

**Comment by cah-joeymadich** [comment]
Still getting the 422 response from github packages... The only way I can seem to get it to publish successfully is if the artifact version is bumped (e.g. 2.3.1-SNAPSHOT -> 2.3.2-SNAPSHOT) which is strange considering SNAPSHOTs should be allowed to be updated/overwritten with changes. If I try to make changes to a SNAPSHOT version and publish I always run into the following error.

**Comment by djspiewak** [comment]
> Still getting the 422 response from github packages... The only way I can seem to get it to publish successfully is if the artifact version is bumped (e.g. 2.3.1-SNAPSHOT -> 2.3.2-SNAPSHOT) which is strange considering SNAPSHOTs should be allowed to be updated/overwritten with changes. If I try to make changes to a SNAPSHOT version and publish I always run into the following error.

Ah! This is very interesting. I haven't experimented with this (I simply don't use `-SNAPSHOT` versions), but I wonder if GitHub Packages lacks the magic Maven snapshot version support. The majority of the system is oriented around version immutability, to the point where releases are not even deleteable on public packages, so it wouldn't at all surprise me if they simply didn't implement this. My guess is that you cannot use `-SNAPSHOT` versions in the way you would normally expect.

Not that this is a bad thing, IMO. :-) Unstable snapshots (i.e. versions that you overwrite) are really bad practice and result in unstable and unreproducible downstream builds. You're usually better off using something like hash snapshots.

Also sorry for losing track of this issue. It fell off my notifications for some reason. Is the `-SNAPSHOT` use-case the only situation where errors are arising?
