### ISSUE TITLE
Plugin not found?

### ISSUE THREAD

**Issue by coding-red-panda** [djspiewak/sbt-github-packages#47]
Hello,

So I've followed the README to get this plugin to work, but it seems it cannot be found on any of the public repositories?

```
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
[info] Loading global plugins from /Users/olivar/.sbt/0.13/plugins
[info] Loading project definition from /Users/olivar/RubymineProjects/separo/core/project
[warn]  module not found: com.codecommit#sbt-github-packages;0.5.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.codecommit/sbt-github-packages/scala_2.10/sbt_0.13/0.5.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.codecommit/sbt-github-packages/scala_2.10/sbt_0.13/0.5.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   /Users/olivar/.ivy2/local/com.codecommit/sbt-github-packages/scala_2.10/sbt_0.13/0.5.3/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/codecommit/sbt-github-packages_2.10_0.13/0.5.3/sbt-github-packages-0.5.3.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/olivar/.sbt/preloaded/com.codecommit/sbt-github-packages/0.5.3/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/olivar/.sbt/preloaded/com/codecommit/sbt-github-packages_2.10_0.13/0.5.3/sbt-github-packages-0.5.3.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/com/codecommit/sbt-github-packages_2.10_0.13/0.5.3/sbt-github-packages-0.5.3.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.codecommit#sbt-github-packages;0.5.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.codecommit:sbt-github-packages:0.5.3 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.codecommit:sbt-github-packages:0.5.3 (scalaVersion=2.10, sbtVersion=0.13) (/Users/olivar/RubymineProjects/separo/core/project/plugins.sbt#L7-8)
[warn]            +- default:core-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.codecommit#sbt-github-packages;0.5.3: not found
        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:320)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1555)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1551)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1586)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$122.apply(Defaults.scala:1584)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1589)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1583)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1606)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1533)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1485)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.codecommit#sbt-github-packages;0.5.3: not found
```

This after adding the `addSbtPlugin("com.codecommit" % "sbt-github-packages" % "0.5.3")` to my `plugins.sbt` file.
Am I missing something?

**Comment by coding-red-panda** [comment]
resolved by upgrading sbt
