### ISSUE TITLE
Unable to publish multi-module project to private repo without errors locally and from the Actions

### ISSUE THREAD

**Issue by Fruzenshtein** [djspiewak/sbt-github-packages#9]
I'm going to start using the `sbt-github-packages` plugin. As a first step I tried to setup it for a simple dummy project — it worked locally and in GitHub Actions context. Then I did the same for a simple dummy multi-module project — it worked locally and in GitHub Actions context.

The problem appeared when I tried to do the same setup for a production git repo that contains a library with some common code. This repo is private and belongs to an organization. My GitHub account has full access within the organization.

This project has following structure:

```
lazy val common = project
  .in(file("lib/common"))
  .settings(sdk.GlobalSettingsGroup)

lazy val `sdk-a` = project
  .in(file("lib/sdk-a"))
  .settings(sdk.GlobalSettingsGroup)
  .dependsOn(common)

lazy val `sdk-b` = project
  .in(file("lib/sdk-b"))
  .settings(sdk.GlobalSettingsGroup)
  .dependsOn(common)

...

lazy val `domain-api-a` = project
  .in(file("domain/domain-api-a"))
  .settings(sdk.GlobalSettingsGroup)
  .dependsOn(`sdk-a`)

lazy val `domain-api-b` = project
  .in(file("domain/domain-api-b"))
  .settings(sdk.GlobalSettingsGroup)
  .dependsOn(`sdk-a`, `sdk-b`)

lazy val domainApis: Seq[ProjectReference] = Seq(
  `domain-api-a`,
  `domain-api-b`,
  ...
)

lazy val libs: Seq[ProjectReference] = Seq(
  `common`,
  `sdk-a`,
  `sdk-b`,
  ...
)

lazy val all = domainApis ++ libs

lazy val root = project
  .in(file("."))
  .aggregate(all: _*)
  .settings(
    name := "foundation-backend"
  )
  .settings(sdk.GlobalSettingsGroup)
```

In general there are 19 submodules.

Here is `GlobalSettingsGroup`:

```
val GlobalSettingsGroup: Seq[Setting[_]] = Seq(
      githubOwner := "private_org_name",
      githubRepository := "foundation-backend",
      credentials +=
        Credentials(
          "GitHub Package Registry",
          "maven.pkg.github.com",
          sys.env.get("GITHUB_ACTOR").getOrElse("N/A"),
          sys.env.getOrElse("GITHUB_TOKEN", "N/A")
        ),
  //scala version, organization, version etc are also here
)
```

I added both env variables to the `.bash_profile`:

```
export GITHUB_TOKEN=my_secret_token_for_github
export GITHUB_ACTOR="Fruzenshtein"
```

When I run `sbt publish` locally I see how all of the packages appear on the packages page of the foundation-backend repo. But SBT command ends with these errors:

```
[error] javax.net.ssl.SSLProtocolException: Broken pipe (Write failed)
[error]         at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
[error]         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
[error]         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
[error]         at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
[error]         at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:988)
[error]         at okio.Okio$1.write(Okio.java:78)
[error]         at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
[error]         at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
[error]         at okio.RealBufferedSink.write(RealBufferedSink.java:41)
[error]         at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
[error]         at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
[error]         at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
[error]         at okhttp3.RequestBody$3.writeTo(RequestBody.java:118)
[error]         at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error]         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error]         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error]         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error]         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error]         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error]         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
```

When I try to tun the same build in context of GitHub Actions using these steps:

```
name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package JAR
        run: sbt publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
```

I get these errors, and no packages published to the packages:

```
[error]   sdk-a / githubActor from sdk-a / credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
[error] 
[error]   sdk-b / githubActor from sdk-b / credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
[error] 
[error]   sdk-c / githubActor from sdk-c / credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
[error] 
[error]   domain-api-a / githubActor from domain-api-a / credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
[error] 
[error]   domain-api-b / githubActor from domain-api-b / credentials ((sbtghpackages.GitHubPackagesPlugin.authenticationSettings) GitHubPackagesPlugin.scala:54)
...
```

I'll be glad to consider any sort of hints, since I already tried approach with:

```
githubTokenSource := TokenSource.Environment("GITHUB_TOKEN")
githubActor := sys.env.get("GITHUB_ACTOR").getOrElse("N/A")
```

instead of direct leverage of `Credentials`

**Comment by djspiewak** [comment]
My guess? POMs probably have to go last when we push. I'm going to play around with this today and get back to you. Definitely seems like a bug.

**Comment by Fruzenshtein** [comment]
@djspiewak thanks
Just a side note — one of the submodules is an auto-plugin. It is used as an entry point to all other dependencies when it goes to use them.

**Comment by djspiewak** [comment]
@Fruzenshtein Sorry for the delay… Finally got around to playing with this. I wasn't able to reproduce the issue at all. Not sure why, exactly. Here was my attempt: https://github.com/djspiewak/packages-test

**Comment by krmannix** [comment]
I also encountered this issue with two separate multi-module projects. I then attempted to upload just a single build by changing `build.sbt` file to only include a single submodule, and still encountered the issue. I also tried to use `sbt <myproject>/publish` as a workaround, but it failed with the same `Broken pipe` exception.

This error seemed to happen immediately after publishing the `.pom` file for the project.
```
[info] Done packaging.
[info] 	published <project name> to https://maven.pkg.github.com/<project>.pom
[error] java.net.SocketException: Broken pipe (Write failed)
[error] 	at java.net.SocketOutputStream.socketWrite0(Native Method)
[error] 	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
[error] 	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
[error] 	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:431)
[error] 	at sun.security.ssl.OutputRecord.write(OutputRecord.java:417)
[error] 	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:886)
[error] 	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:857)
[error] 	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
[error] 	at okio.Okio$1.write(Okio.java:78)
[error] 	at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
[error] 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
[error] 	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
[error] 	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
[error] 	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
[error] 	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:99)
[error] 	at okhttp3.RequestBody$3.writeTo(RequestBody.java:118)
[error] 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error] 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
[error] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
[error] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
[error] 	at okhttp3.RealCall.execute(RealCall.java:69)
[error] 	at sbt.internal.librarymanagement.ivyint.GigahorseUrlHandler.upload(GigahorseUrlHandler.scala:185)
[error] 	at org.apache.ivy.util.url.URLHandlerDispatcher.upload(URLHandlerDispatcher.java:82)
[error] 	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
[error] 	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:365)
[error] 	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put(ConvertResolver.scala:117)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$ChecksumFriendlyURLResolver.put$(ConvertResolver.scala:104)
[error] 	at sbt.internal.librarymanagement.ConvertResolver$$anonfun$defaultConvert$lzycompute$1$PluginCapableResolver$1.put(ConvertResolver.scala:164)
[error] 	at org.apache.ivy.plugins.resolver.RepositoryResolver.publish(RepositoryResolver.java:216)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5(IvyActions.scala:492)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$5$adapted(IvyActions.scala:491)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:929)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:929)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:491)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$3(IvyActions.scala:141)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:154)
[error] 	at sbt.internal.librarymanagement.IvyActions$.withChecksums(IvyActions.scala:148)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1(IvyActions.scala:141)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$publish$1$adapted(IvyActions.scala:131)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:243)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:242)
[error] 	at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:131)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2240)
[error] 	at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2239)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:66)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:271)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (<project name> / publish) java.net.SocketException: Broken pipe (Write failed)
```

I can see the `.pom` file, but no other files appear to upload.

I have `GITHUB_TOKEN` in my environment, and I only added `githubOwner` and `githubRepository` to my `build.sbt` file. The sbt version in use is `1.1.1`.

Thanks for putting together this plugin - the instructions were very thorough and it was easy to adopt to our project for both resolving and publishing. Happy to help with attempting to fix this issue if I can!
